version: '3.9'
services: 
  ashu-flaskapp: 
    image: chrp-flask:uniappv1 
    build: 
      context: .  # location of dockerfile 
      dockerfile:  Dockerfile # name of dockerfile
    container_name: chrppyc1 
    ports:
    - 4997:5000  
# above steps have merging of build and run 